### ISSUE TITLE
Cortex Labs

### ISSUE THREAD

**Issue by glai9665** [steven2358/awesome-blockchain-ai#1]
Surprised that Cortex Labs is not on this list. Literally the ONLY blockchain with a virtual machine that allows you to execute AI programs on-chain right now.

**Comment by steven2358** [comment]
Surprising indeed, considering how simple Pull Request technology (TM) is compared to AI and blockchain tech.

Anyways, here ya go: 6d322dd96af02f0378c16e8f9ec635f3796260d4
