### ISSUE TITLE
[Discussion] - Further Classifications for Listed Projects - Reliability and Legitimacy of Listed Projects

### ISSUE THREAD

**Issue by walidmujahid** [steven2358/awesome-blockchain-ai#5]
I like this list very much and for functioning as a starting point to find these projects, this list does the job.

However, perhaps this list could save people work at trying to also figure out which projects actually exist or are scams. If projects claims to have a network at some stage in development -e.g computation networks like AI Crypto-, how reliable is it? 

Perhaps that could be a bit too much for limited contributors as I suppose it would require testing a network. However nice such information would be to have done for us already, perhaps at least a criteria for discrimination could be put in place to see how legitimate a project is -e.g, is it an outright scam? Do their claimed investors actually exist? Does their team actually exist? Does their team have the required skills? Do they only have advisory boards and nothing much else? etc.

I am putting this forward for a discussion starter as opposed to a Feature Request. I do realise what I am saying could be summarised as to 'wanting the contributors to give their reviews of the projects'; which could be counterproductive, biased, or just not work at all in the first place as the list already serves its most simple function -i.e being a place that documents these kinds of projects. However, more detailed classification based on some criteria could be very helpful and just nice to have. But perhaps this should be a separate project.

**Comment by steven2358** [comment]
A few words on the reliability of the current projects:

I do some minimal screening before including projects in this list, and up till now I have gone with my gut. Many projects have actually been discarded this way. But lesser projects may indeed slip through, so your suggestion is very valid.

Also, there's a deadpool at the bottom of the list now, which holds the projects that were once part of the list but have been deactivated. Most of them simply went offline at some point.

Finally, I more or less regularly ping each project on the list to check if they are still active. Scams usually go bust at some point, so if a project has been part of the list for a long time this should indicate that it is a serious project.

As for your suggestion, I assume the classification could be implemented by adding a table with features. Or maybe a list of checkboxes for each project. Right?
